<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="6"
           failures="3"
           errors="0"
           skipped="1"
           time="0.023">
  <properties />
            <testcase name="TestFunctionSiventh" time="0.001" classname="com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping">
                <failure type="java.lang.AssertionError"
                  message="null"
              >
<![CDATA[java.lang.AssertionError: null
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.assertNotEquals(Assert.java:1157)
  org.testng.Assert.assertNotEquals(Assert.java:1162)
  org.testng.asserts.Assertion$62.doAssert(Assertion.java:665)
  org.testng.asserts.Assertion.executeAssert(Assertion.java:30)
  org.testng.asserts.Assertion.doAssert(Assertion.java:15)
  org.testng.asserts.Assertion.assertNotEquals(Assertion.java:662)
  com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping.TestFunctionSiventh(parallelRunWithPriorityAndGrouping.java:87)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
            <testcase name="TestFunctionFourth" time="0.002" classname="com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [11] but found [10]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [11] but found [10]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping.TestFunctionFourth(parallelRunWithPriorityAndGrouping.java:62)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
            <testcase name="TestFunctionSecond" time="0.003" classname="com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [11] but found [10],
	null,
	expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [11] but found [10],
	null,
	expected [false] but found [true]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping.TestFunctionSecond(parallelRunWithPriorityAndGrouping.java:42)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
            <testcase name="TestFunctionFifth" time="0.0" classname="com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping">
          <skipped />
    </testcase>
  
            <testcase name="TestFunctionSixth" time="0.002" classname="com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping" />
                <testcase name="TestFunctionThird" time="0.014" classname="com.org.TestNGPracticeCode.TestNgPractice.parallelRunWithPriorityAndGrouping" />
      
</testsuite>
